### ISSUE TITLE
Default std async transport with dangling goroutine

### ISSUE THREAD

**Issue by cog-qlik** [rollbar/rollbar-go#48]
Let's say I want to integrate this rollbar client to a custom logger only if the user opts for it.
The problem is that [this](https://github.com/rollbar/rollbar-go/blob/master/rollbar.go#L34) line
```
std = NewAsync("", "development", "", hostname, "")
```
always gets executed just importing the library in another package, even though I may not use any other functionality (eg. if a user of my custom logger doesn't need rollbar at all).

This results in a dangling goroutine like the following
```
1 @ 0x45780b 0x4578b3 0x42e88b 0x42e66b 0x9a3404 0x4865c1
#    0x9a3403    github.com/rollbar/rollbar-go.NewAsyncTransport.func1+0x83    /home/gian/Documents/Projects/go/pkg/mod/github.com/rollbar/rollbar-go@v1.0.2/async_transport.go:51
```

generated by [this](https://github.com/rollbar/rollbar-go/blob/master/async_transport.go#L50-L78) portion of code.

It whould be nice to have a constructor of the rollbar client instead of having one that is created by default, with no way of interrupting that goroutine.

**Comment by rokob** [comment]
Yeah this is doable, it will require a version bump as it will be a breaking change because the new behavior would result in nothing getting sent until someone calls the init. There already is a constructor if you don't want to use the default one. The overhead of a single goroutine is pretty minimal. Perhaps we should make close on the transport actually close the channel which will terminate the range loop and therefore exit the goroutine. We can then add Close to the top level which will close the std one. Auto opening it just to have it closed is a tiny bit wasteful but that would be backwards compatible.

**Comment by cog-qlik** [comment]
Yes, I realized that implementing a different initialization mechanism implies a breaking change. Leaving the importer package the ability to decide whether to run goroutines in the back or not is preferrable IMHO.

@rokob adding a `Close()` function to stop that dangling goroutine if the std transport is not required at least gives a way to get rid of the problem and, at the same time, it's a backwords-compatible change. It could be a good compromise.
