### ISSUE TITLE
Can I grab crashes in goroutines?

### ISSUE THREAD

**Issue by weiyixuan** [rollbar/rollbar-go#50]
I use rollbar.WrapAndWait()，but cannot grab crash in goroutines?

**Comment by rokob** [comment]
What do you mean by grab? You should be able to call:

`go Rollbar.WrapAndWait(f)`

and you will report panics that occur while executing `f` as long as `f` does not create a new goroutine.

But if you mean that you have a function `f` which spawns a goroutine and a panic might occur inside that new goroutine, calling `WrapAndWait(f)` will not capture those panics. There is no way to write a generic wrapper function in Go which does that. See https://github.com/golang/go/issues/20161 for one instance. This is by design of the language.
