### ISSUE TITLE
Unable to get IP addresses in gin middleware.

### ISSUE THREAD

**Issue by piyushdivyankar1994** [rollbar/rollbar-go#93]
I have written following middleware based on github.com/gin-contrib/rollbar, I would like to have IP address from the context be sent to rollbar. But I am only able to do it as a custom variable. 
```
func Recovery(onlyCrashes bool) gin.HandlerFunc {

	return func(c *gin.Context) {
		defer func() {

			if rval := recover(); rval != nil {
				debug.PrintStack()

				// rollbar.SetEndpoint(c.Request.RequestURI)
				rollbar.SetItemsPerMinute(20)
				rollbar.SetPerson(strconv.FormatInt(c.Keys["remote_id"].(int64), 10), "", "")
				rollbar.Critical(errors.New(fmt.Sprint(rval)), map[string]interface{}{
					"endpoint":  c.Request.RequestURI,
					"person.Id": c.Keys["remote_id"].(int64),
                                        "IPAddress": c.ClientIP(),
				})

				c.AbortWithStatus(http.StatusInternalServerError)
			}

			if !onlyCrashes {
				for _, item := range c.Errors {
					rollbar.Error(item.Err, map[string]string{
						"meta":     fmt.Sprint(item.Meta),
						"endpoint": c.Request.RequestURI,
					})
				}
			}
		}()

		c.Next()
	}
}
```
How can I properly log IP address in gin.context on rollbar. This doesn't show up in IPAddresses Tab on rollbar console.

**Comment by pawelsz-rb** [comment]
@piyushdivyankar1994, so this one is really tricky. First you need to log the request together with your error: 
```
rollbar.Critical(errors.New(fmt.Sprint(rval)), c.Request, map[string]interface{}{
```
however, there is a bug in go-sdk. Basically, by default it will return the IP:port, and we don't expect port. I will put a fix for that soon. In the meantime, you can set your header in the middleware or part of every request:
```
c.Request.Header.Add("X-Real-IP", c.ClientIP())
```
Otherwise, it won't work.  (you don't really need extra `IPAddress` field, but it won't hurt to have it. 

Please let me know if you have any questions

**Comment by pawelsz-rb** [comment]
closing for now
